language:
  ruby

rvm:
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head

  fast_finish:
    true

env:
  global:
    - OTM_BASE=/tmp/ontopia
    - ONTOPIA_VERSION=5.3.0

script:
  rake spec

install:
  - gem install nuggets
  - gem install --prerelease --development ontopia-topicmaps

before_install:
  - wget https://github.com/ontopia/ontopia/releases/download/release-$ONTOPIA_VERSION/ontopia-$ONTOPIA_VERSION.zip -O $OTM_BASE.zip
  - unzip $OTM_BASE.zip -d $OTM_BASE

sudo:
  false
