language:
  ruby

rvm:
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head

  fast_finish:
    true

script:
  rake spec

install:
  gem install --development ontopia-topicmaps

before_install:
  - sudo wget http://ontopia.googlecode.com/files/ontopia-5.3.0.zip -O /usr/local/ontopia.zip
  - sudo unzip /usr/local/ontopia.zip -d /usr/local/ontopia
