language:
  ruby

rvm:
  - jruby-19mode
  - jruby-head

matrix:
  allow_failures:
    - rvm: jruby-head

  fast_finish:
    true

env:
  global:
    - OTM_BASE=/tmp/ontopia

script:
  rake spec

install:
  - gem install nuggets
  - gem install --prerelease --development ontopia-topicmaps

before_install:
  - wget http://ontopia.googlecode.com/files/ontopia-5.3.0.zip -O $OTM_BASE.zip
  - unzip $OTM_BASE.zip -d $OTM_BASE

sudo:
  false
